[package]
name = "rustabelle"
version = "0.1.0"
authors = ["Sebastian Ullrich <sebasti@nullri.ch>"]

[dependencies]
itertools = "0.4.0"
petgraph = "0.2.5"
toml = { git = "https://github.com/alexcrichton/toml-rs" }  # for https://github.com/alexcrichton/toml-rs/pull/89
