[package]
name = "rustabelle"
version = "0.1.0"
authors = ["Sebastian Ullrich <sebasti@nullri.ch>"]

[dependencies]
itertools = "0.4.0"
petgraph = "0.1.*"

[dependencies.rustc_mir]
path = "librustc_mir/src/librustc_mir/"
