rustc_args = "../rust/src/libcore/lib.rs"
ignore = [
  "core_mem_swap",
]
targets = [
  "core_slice__T__SliceExt_binary_search",
]

[traits.core_slice_SliceExt]
# only method called from default methods, everything else should be static calls
only = ["len"]
